### ISSUE TITLE
build to production

### ISSUE THREAD

**Issue by ngocnveva** [simpulton/angular2-website-routes#11]
how to build and deploy to apache http, please!

**Comment by jdgarvey** [comment]
Hi @ngocnveva,

You can do this by running `ng build --prod` in the root directory of the project. This will create a `dist` directory with `index.html`, all your webpack bundles, and all your assets. All you need to do from there is upload the contents of `dist` to your hosting provider via FTP.

The only "gotcha" is with routing in HTML5 mode. Refreshing any route will result in a 404, so you will need to modify `.htaccess` on your server. Details about how to do that can be found [here](https://angular.io/guide/deployment#production-servers). Thanks!
