### ISSUE TITLE
fem-simple app isn't working

### ISSUE THREAD

**Issue by anthonybrown** [simpulton/angular2-website-routes#5]
Just cloned the fem simple app repo from the workshop, it's not building, and I can't seem to figure out how to fix it.

**Comment by dungeondevil17** [comment]
I am experiencing an issue running 'npm start' -->

ERROR in [default] C:/Projects/emerald-angular/app3/node_modules/rxjs/Observable.d.ts:1:0
Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.

ERROR in [default] C:/Projects/emerald-angular/app3/node_modules/rxjs/Observable.d.ts:12:5
Cannot find name 'Symbol'.

ERROR in [default] C:/Projects/emerald-angular/app3/node_modules/rxjs/Observable.d.ts:15:41
Cannot find name 'Iterable'.

**Comment by jdgarvey** [comment]
This should be fixed

**Comment by dungeondevil17** [comment]
this is working now.  appreciate the quick fix!

**Comment by anthonybrown** [comment]
I can confirm it's working again 👍

**Comment by jdgarvey** [comment]
Fantastic, thanks guys!
