### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by wonderdogone** [simpulton/angular2-website-routes#7]
npm install

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.0.0-rc.1 wants rxjs@5.0.0-beta.6

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jwalters1/Downloads/angular2-website-routes-master/npm-debug.log

**Comment by jdgarvey** [comment]
@wonderdogone we locked down the rxjs beta version to `beta.6` and that resolved the issue. We do, however, recommend updating to the latest Node and NPM versions :)
